### ISSUE TITLE
External enumeration is not supported

### ISSUE THREAD

**Issue by sbfkcel** [rollup/rollup-plugin-typescript#120]
use `typescript.transpileModule` External enumeration is not supported

Please update

---

## Example 

**getNetworkType.ts**

```typescript
/// <reference path="./getNetworkType.d.ts" />

let getNetworkType = ():Network=>{
    return Network.A;
};

export default getNetworkType;
```

**getNetworkType.d.ts**

```typescript
declare const enum Network {
    A = 1
}
```

```bash
tsc getNetworkType.ts   # normal，return 1
```

```javascript
typescript.transpileModule    // error, return Network.A
```

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
