### ISSUE TITLE
[documentation improvement] Request some info on Babel

### ISSUE THREAD

**Issue by mesqueeb** [rollup/rollup-plugin-typescript#125]
So I am new to Typescript and trying to refactor some old JS helper modules into TS ones.

I always used a standard Rollup setup with the **babel plugin**:
```js
plugins = [
  babel({
    exclude: 'node_modules/**' // only transpile our source code
  }),
]
```
#### And .babelrc
```js
{
  "presets": [
    ["@babel/preset-env", {
      "modules": false
    }]
  ],
  "plugins": [
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```

Now I'm rewriting my files in typescript. Should I just **delete .babelrc and change the rollup plugins to:**
```js
plugins = [
  typescript()
]
```
Or keep my `.babelrc` and the babel plugin as well?

My humble request is to add a little section on this to the Readme because I think a lot of people new to TypeScript will struggle with this. Or if someone can give advice here, I'll make a PR for the readme!

Thanks so much guys!!!

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
