### ISSUE TITLE
Any hope to finally see TypeScript errors?

### ISSUE THREAD

**Issue by Ventajou** [rollup/rollup-plugin-typescript#126]
I see that 1.0.0 was released recently 🎉 

However, it still doesn't appear to report TypeScript compilation error. There was a ticket about that which was closed because some PR was supposed to fix it, but the PR is from last year and was never merged.

Any plans to change this? It would really be useful in a CI setup

**Comment by guybedford** [comment]
This is important, yes.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
