### ISSUE TITLE
Use module resolution strategy implied by tsconfig

### ISSUE THREAD

**Issue by anandthakker** [rollup/rollup-plugin-typescript#127]
Currently, this plugin uses `nodeModuleNameResolver` to resolve module ids:

https://github.com/rollup/rollup-plugin-typescript/blob/7f553800b90fc9abdcd13636b17b4824459d3960/src/index.js#L70

TypeScript [specifies two strategies for module resolution](https://www.typescriptlang.org/docs/handbook/module-resolution.html) -- "classic" and "node".  The strategy to be used can be configured in `tsconfig.json`; and, confusingly enough, the default strategy depends on the module output type.

According to the TS [API docs](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#customizing-module-resolution), there's a `resolveModuleName` function that looks like it chooses the appropriate strategy based on the given ts config: https://github.com/Microsoft/TypeScript/blob/05716a74a50533796e82388d861cfba927f3fdea/src/compiler/moduleNameResolver.ts#L615-L637

Would it make sense to use that function instead of `nodeModuleNameResolver`, so that this plugin will resolve imports from TS files the same way that TS itself would?

**Comment by ezolenko** [comment]
In the docs they have:
```[classic] used to be TypeScript’s default resolution strategy. Nowadays, this strategy is mainly present for backward compatibility.```

This is not quite as strong as `deprecated`, but close enough.

**Comment by Kinrany** [comment]
I'm interested in this. Seems easy enough, I'd be happy to contribute if I can.

**Comment by Kinrany** [comment]
I mean, can I?

I'm trying to start using rollup in a large project. Haven't managed to successfully build it yet, but simply replacing `nodeModuleNameResolver` with `classicNameResolver` based on `compilerOptions.moduleResolution` seems to work.

There's no CONTRIBUTING.md, so I'm not sure how to proceed.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
