### ISSUE TITLE
Tree-shaking tslib

### ISSUE THREAD

**Issue by jeffijoe** [rollup/rollup-plugin-typescript#139]
TSLib now ships a `tslib.es6.js` which has `export`s.

I tried specifying it using `tslib: require('tslib/tslib.es6.js')` but getting `Unexpected token export`.

Is this (going to be) supported?

Thanks for the awesome plugin!

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
