### ISSUE TITLE
Custom tslib does not work

### ISSUE THREAD

**Issue by sntran** [rollup/rollup-plugin-typescript#141]
I was looking at the source at https://github.com/rollup/rollup-plugin-typescript/blob/6c433a6c482e3f36f01c83c5be130387da699c9c/src/index.js#L85

I fail to understand how it would work with custom `tslib` per example on the README.

The load hook requires a return of string, a { code, map } object, or nothing/null. If I set `tslib` option to `require('tslib')`, it will fail that requirement.

If not set that option, it works because [`tslib` is read from filesystem as string](https://github.com/rollup/rollup-plugin-typescript/blob/6c433a6c482e3f36f01c83c5be130387da699c9c/src/index.js#L23-L24).

Or am I missing something?

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
