### ISSUE TITLE
XrmEnum.FormType.Create is not resolve properly

### ISSUE THREAD

**Issue by rojorioko** [rollup/rollup-plugin-typescript#148]
When bundling out index.ts file, the XrmEnum.FormType.Create is not being compiled to correct value.  Is it an existing for Enums?
[test2.zip](https://github.com/rollup/rollup-plugin-typescript/files/3732439/test2.zip)

**Comment by rojorioko** [comment]
Hello, just wanted to check if there is an update?

Thank You,

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:

**Comment by rojorioko** [comment]
Hi Andrew,

I tried building my project using latest version on Rollup and XrmEnum is
still not resolve.
Please transfer the issue to the new repo. Thank you :)

Kind Regards,
Carlo
