### ISSUE TITLE
jsx: `preserve` does not compile

### ISSUE THREAD

**Issue by zanona** [rollup/rollup-plugin-typescript#149]
Hi,
I'm trying to compile `.tsx` preserving the JSX output but have a problem whenever using `jsx: 'preserve'`. It only works when using `jsx: 'react'` but it's not the output I'm looking for.
Any ideas or workarounds or am I missing something?

Thanks

<details>
<summary><b>rollup.config.json</b></summary>

```js
import typescript from 'rollup-plugin-typescript';

export default {
	output: {name: 'foo', format: 'iife'},
	plugins: [
		typescript({
			jsx: 'preserve',
			target: 'esnext',
			lib: ['es5', 'es6', 'dom']
		})
	]
};
```

</details>

<details>
<summary><b>main.tsx</b></summary>

```tsx
export default <span>Yo!</span>
```
</details>

```bash
rollup -c -- main.tsx
```

```bash
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
lib/scripts/main.tsx (1:15)
1: export default <span>Yo!</span>
                  ^
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
```

**Comment by bhabgs** [comment]
I had the same problem，for vue tsx!

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:

**Comment by zanona** [comment]
@shellscape

**Comment by bhabgs** [comment]
I've solved the problem
