### ISSUE TITLE
Error: [type] is not exported by [file]

### ISSUE THREAD

**Issue by Vehmloewff** [rollup/rollup-plugin-typescript#151]
This code:

```ts
import { Type1, Type2 } from './file.ts';

export {
	Type2
}

export const fn1: Type1 = () => {
	// ...
}
```

Throws this error in the console:

```
[!] Error: 'Type2' is not exported by src/file.ts
```

Is there any workaround or fix for this?

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:

**Comment by Vehmloewff** [comment]
Thanks for responding!

I think that this issue is still relevant @shellscape.  I would be glad to know that it will be transferred to the new repo.
